spring:
  application:
    name: spring-cloud-eureka-client  #bu isimle register olur eureka server'a
server:
  port: 0 #rastgele musait bir portta çalışacak
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true